version: '3.7'

networks:
  blue_lion:

services:
  postgres:
    container_name: blue-lion-postgres
    hostname: postgres
    image: postgres
    networks:
      - blue_lion
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    restart: unless-stopped

  redis:
    container_name: blue-lion-redis
    hostname: redis
    image: 'redis:alpine'
    networks:
      - blue_lion

  frontend:
    container_name: blue-lion-front-end
    build:
      context: ./front-end
    networks:
      - blue_lion

  balaner:
    container_name: blue-lion-balancer
    build:
      context: ./balancer
    ports:
      - 9090:9090
    networks:
      - blue_lion

  backend1:
    container_name: blue-lion-backend1
    hostname: backend1
    build:
      context: ./backend
    networks:
      - blue_lion

  backend2:
    container_name: blue-lion-backend2
    hostname: backend2
    build:
      context: ./backend
    networks:
      - blue_lion
